# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdirectory', '0002_auto_20171026_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bloodg_roup',
            new_name='blood_group',
        ),
    ]
