# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import studentdirectory.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studentdirectory', '0003_auto_20171026_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=studentdirectory.models.student_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdirectory.StudentImage'),
        ),
    ]
