# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdirectory', '0004_auto_20171030_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentdirectory.StudentImage'),
        ),
    ]
