# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdirectory', '0005_auto_20171031_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='permenant_add',
            new_name='permanent_add',
        ),
        migrations.AlterUniqueTogether(
            name='studentimage',
            unique_together=set([('uid', 'file')]),
        ),
    ]
