# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdirectory', '0006_auto_20171102_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tranfered_out_date',
            new_name='transfered_out_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tranfered_out_reason',
            new_name='transfered_out_reason',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tranfered_out_to_school',
            new_name='transfered_out_to_school',
        ),
    ]
